### ISSUE TITLE
Docker image has broken (x86_64)

### ISSUE THREAD

**Issue by Ryonez** [woahbase/alpine-searx#1]
As of the latest update, searches no longer work.

Broken build: https://hub.docker.com/layers/woahbase/alpine-searx/x86_64/images/sha256-be238cb2de1820371268df242eba440f5f1d5517610ec75ddf326239c483e978?context=explore

Unable to revert to older builds as they've been deleted.

Error from log:
```
Traceback (most recent call last):
File "/usr/local/searx/searx/engines/google.py", line 253, in response
url = eval_xpath(result, href_xpath)[0]
IndexError: list index out of range
ERROR:searx.google engine:list index out of range
Traceback (most recent call last):
File "/usr/local/searx/searx/engines/google.py", line 253, in response
url = eval_xpath(result, href_xpath)[0]
IndexError: list index out of range
```

**Comment by Ryonez** [comment]
Annnnnd now it's suddenly started working.

Somewhat frustrating that I can't figure out the case. Came here as the build is the only recent change. I'm going to close this as I don't think this was the case.
